datafile <- "household_power_consumption.txt"
data <- read.table(datafile, sep = ";", header = T, na.strings = "?")
finaldata <- data[data$Date %in% c("1/2/2007","2/2/2007"),]
settime <-strptime(paste(finaldata$Date, finaldata$Time, sep=" "),"%d/%m/%Y %H:%M:%S")
finaldata <- cbind(settime, finaldata)
par(mfrow = c(2, 2))
# plot 1 (NW)
plot(finaldata$settime, finaldata$Global_active_power, type = "l", ylab = "Global Active Power", xlab = "")
# plot 2 (NE)
plot(finaldata$settime, finaldata$Voltage, type = "l", ylab = "Voltage", xlab = "datetime")
# plot 3 (SW)
plot(finaldata$settime, finaldata$Sub_metering_1, type = "l", ylab = "Energy sub metering", xlab = "", col = "black")
points(finaldata$settime, finaldata$Sub_metering_2, type = "l", xlab = "", ylab = "Sub_metering_2", col = "red")
points(finaldata$settime, finaldata$Sub_metering_3, type = "l", xlab = "", ylab = "Sub_metering_3", col = "blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), bty="n", cex=.5)
# plot 4 (SE)
plot(finaldata$settime, finaldata$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power", ylim = c(0, 0.5))
dev.copy(png, file="plot4.png", width=480, height=480)
dev.off()